// Generated by https://quicktype.io

export interface CategoryResponse {
    ok:         boolean;
    categories?: Category[];
    category?: Category;
}

export interface Category {
    _id?:       string;
    name:      string;
    createdAt?: string;
    updatedAt?: string;
}
