// Generated by https://quicktype.io

export interface AuthResponse {
    _id:          string;
    username:     string;
    roles:        string[];
    access_token: string;
};

export interface AuthResponseShort {
    access_token: string;
}
