// Generated by https://quicktype.io

export interface SalesResponse {
    ok:    boolean;
    sales?: Sale[];
    sale?: Sale;
}

export interface Sale {
    _id:        string;
    customer:   Customer;
    user:       User;
    products:   ProductElement[];
    totalPrice: number;
    createdAt:  string;
    updatedAt:  string;
}

export interface Customer {
    _id:            string;
    documentNumber: string;
    name:           string;
    address?:       string;
    phoneNumber:    string;
    createdAt:      string;
    updatedAt:      string;
}

export interface ProductElement {
    _id:      string;
    product:  Product;
    quantity: number;
}

export interface Product {
    status:    number;
    _id:       string;
    name:      string;
    price:     number;
    imageURL:  string;
    stock:     number;
    category:  Category;
    createdAt: string;
    updatedAt: string;
}

export interface Role {
    _id:       string;
    name:      string;
    createdAt: string;
    updatedAt: string;
}

export interface Category {
    _id:       string;
    name:      string;
    createdAt: string;
    updatedAt: string;
}

export interface User {
    roles:     Role[];
    _id:       string;
    username:  string;
    email:     string;
    password:  string;
    createdAt: string;
    updatedAt: string;
}
